apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: wordpress
  ports:
    - port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050