apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: ftps
  ports:
    - protocol: TCP
      name: ftp
      port: 21
      targetPort: 21
    - port: 30021
      targetPort: 30021
      nodePort: 30021
      name: ftppassive21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30021